ardana-dev-tools enhancements (SOC-7471)
The ardana-dev-tools tooling will now create a cloud-vagrant symlink
under the ardana-dev-tools directory that points to the active cloud's
ardana-vagrant-models directory. Most of the relevant utility commands
should now support being run outside of the vagrant model directory
and will automatically cd to the cloud-vagrant link'd directory when
run.

Added some new utility commands to the bin directory:
  * ardana-nodes
    Reports the nodes that make up the cloud, as defined in the
    configured cloud's astack-ssh-config settings.
  * ardana-ssh
    Runs ssh with the specified arguments, using the configured
    cloud's astack-ssh-config settings.
  * ardana-scp
    Runs scp with the specified arguments, using the configured
    cloud's astack-ssh-config settings.
  * ardana-rsync
    Runs rsync with the specified arguments, using the configured
    cloud's astack-ssh-config settings.
  * ardana-run-tests
    Run the bin/deployer/run-tests.sh script on the deployer node with
    the specified arguments

Updated some of the existing tools to leverage these scripts or their
supporting mechanisms.

Add --no-setup option to the bin/cleanup-slave command which skips the
dev-env-setup --vagrant-only step; for developer use when the Vagrant
environment is known to already be setup correctly. cleanup-slave will
also attempt to destroy the active cloud via the cloud-vagrant symlink
if it exists, which is faster than the fall back mechanism destroying
Vagrant instances one at a time.

Updated the README.md to better reflect these and other recent changes.

Change-Id: I0ccfa30f31a37c30c69302d725d692ca1b586d15

diff --git a/bin/cleanup-slave b/bin/cleanup-slave
--- a/bin/cleanup-slave
+++ b/bin/cleanup-slave
@@ -34,19 +34,22 @@ usage() {
   echo
   echo "--ci              -- Sets the same options as used by the CI"
   echo "                     environment."
+  echo "--no-setup        -- Skip the Vagrant env setup step."
 }
 
-OPTIONS=help,ci
+OPTIONS=help,ci,no-setup
 TEMP=$(getopt -o -h -l $OPTIONS -n $SCRIPT_NAME -- "$@")
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 eval set -- "$TEMP"
 
 CI=
+NO_SETUP=
 
 while true ; do
     case "$1" in
         -h | --help) usage ; exit 0 ;;
         --ci) CI=1 ; shift ;;
+        --no-setup) NO_SETUP=1 ; shift ;;
         --) shift ; break ;;
         *) break ;;
     esac
@@ -62,9 +65,18 @@ sudo sysctl -w \
 # them with vagrant. If that didn't work, don't worry about it. We'll sweep
 # up any stragglers later using virsh directly.
 if which vagrant ; then
-    eval "$($(dirname "$(readlink -e "${BASH_SOURCE[0]}")")/dev-env-setup --vagrant-only)"
+    if [ -z "${NO_SETUP}" ]; then
+        eval "$($(dirname "$(readlink -e "${BASH_SOURCE[0]}")")/dev-env-setup --vagrant-only)"
+    fi
 
     vagrant --version
+
+    if [ -L "${TOOLS_DIR}/cloud-vagrant" ]; then
+        if ! ${SCRIPT_DIR}/ardana-vagrant destroy -f; then
+            echo "Failed to cleanup configured cloud; falling back on global cleanup."
+        fi
+    fi
+
     # prune stale state
     vagrant global-status --prune || true
     # vagrant allows you to destroy instances from any path provided you
@@ -211,6 +223,9 @@ find $TOOLS_DIR -type f -name .astack_env | xargs rm -vf
 
 # Remove stale locally staged input models
 find $TOOLS_DIR/ardana-vagrant-models -name input-model -type d | xargs rm -vfr
+
+# Remove cloud-vagrant symlink
+rm -f "${TOOLS_DIR}/cloud-vagrant"
 
 # Remove stale cached ISO images
 # Look for any files under the ~/.cache-ardana/isos tree older than
