SCPL-339 Add override repos to Cloud8 deployer and build update RPMS
Define a new set of override repos for the Cloud8 deployer setup,
with one entry pointing at ardana-dev-tools/../NEW_RPMS, which will
be rsync'd to the deployer and added as a zypper repo with priority
98.

Ensure we auto accept zypper GPG keys when running zypper refresh.

NOTE: You will need to manually install the createrepo package and
manually run it against the NEW_RPMS directory before testing this
patch.

The tests for the ardana/next branch are currently checking
out any repos where the sha1 does not match the sha1 in the published
sources.

This adds code to ardana-dev-tools to create RPMs for any repos
that are checkout at the same directory level as ardana-dev-tools
and that we can determine are used when building an RPM.

Change-Id: I6cc3ec33921e458d082b257b24a4cd7170c7124e

diff --git a/ansible/roles/vagrant-cloud8-setup/tasks/setup-local-repos.yml b/ansible/roles/vagrant-cloud8-setup/tasks/setup-local-repos.yml
--- a/ansible/roles/vagrant-cloud8-setup/tasks/setup-local-repos.yml
+++ b/ansible/roles/vagrant-cloud8-setup/tasks/setup-local-repos.yml
@@ -88,6 +88,45 @@
   failed_when:
     - _dir_repos_add_result.rc not in [0, 55]
 
+- name: vagrant-cloud8-setup | setup-local-repos | Check for local override repos
+  stat:
+    path: "{{ c8setup.server.base }}/{{ c8setup.distros[item.distro].dir }}/{{ item.path }}"
+  with_items: c8setup.repos
+  register: _override_repos_result
+  when:
+    - item.distro == ardana_distro
+    - item.enabled | bool
+    - item.override is defined
+
+- name: vagrant-cloud8-setup | setup-local-repos | Setup local override repos
+  become: yes
+  shell: |
+    set -eu
+
+    if ! zypper repos "{{ item.item.alias }}"; then
+      zypper addrepo \
+          --no-check \
+          --no-keep-packages \
+          --no-gpgcheck \
+          --refresh \
+          --priority "{{ item.item.priority | default(0) }}" \
+          --name "{{ item.item.name }}" \
+          "dir://{{ c8setup.server.base }}/{{ c8setup.distros[item.item.distro].dir }}/{{ item.item.path }}" \
+          "{{ item.item.alias }}"
+          exit 55  # arbitrary exit code not generated by zypper as per man page
+    fi
+  register: _override_repos_add_result
+  with_items: _override_repos_result.results
+  when:
+    - not (item | skipped)
+    - item.stat.exists
+  changed_when:
+    - _override_repos_add_result.rc == 55
+  failed_when:
+    - _override_repos_add_result.rc not in [0, 55]
+
 - include: _refresh-repos.yml
   when:
-    - (_iso_repos_add_result | changed) or (_dir_repos_add_result | changed)
+    - ((_iso_repos_add_result | changed) or
+       (_dir_repos_add_result | changed) or
+       (_override_repos_add_result | changed))
diff --git a/ansible/roles/vagrant-cloud8-setup/tasks/setup-remote-repos.yml b/ansible/roles/vagrant-cloud8-setup/tasks/setup-remote-repos.yml
--- a/ansible/roles/vagrant-cloud8-setup/tasks/setup-remote-repos.yml
+++ b/ansible/roles/vagrant-cloud8-setup/tasks/setup-remote-repos.yml
@@ -123,7 +123,62 @@
   tags:
     - rhel
 
+- name: vagrant-cloud8-setup | setup-remote-repos | Check for deployer override repos
+  delegate_to: "{{ deployer_node }}"
+  stat:
+    path: "{{ c8setup.server.base }}/{{ c8setup.distros[item.distro].dir }}/{{ item.path }}"
+  with_items: c8setup.repos
+  register: _override_repos_result
+  when:
+    - item.enabled | bool
+    - item.override is defined
+
+- name: vagrant-cloud8-setup | setup-remote-repos | Setup remote override repos (SLES)
+  become: yes
+  shell: |
+    set -eu
+
+    if ! zypper repos "{{ item.item.alias }}"; then
+      zypper addrepo \
+          --no-check \
+          --no-keep-packages \
+          --no-gpgcheck \
+          --refresh \
+          --priority "{{ item.item.priority | default(0) }}" \
+          --name "{{ item.item.name }}" \
+          "http://{{ deployer_address }}:79/{{ c8setup.distros[item.item.distro].dir }}/{{ item.item.path }}" \
+          "{{ item.item.alias }}"
+          exit 55  # arbitrary exit code not generated by zypper as per man page
+    fi
+  register: _override_repos_add_sles_result
+  with_items: _override_repos_result.results
+  when:
+    - not (item | skipped)
+    - ardana_family == "suse"
+    - item.item.distro == ardana_distro
+    - item.stat.exists
+  changed_when:
+    - _override_repos_add_sles_result.rc == 55
+  failed_when:
+    - _override_repos_add_sles_result.rc not in [0, 55]
+
+- name: vagrant-cloud8-setup | setup-remote-repos | Setup remote override repos (RHEL)
+  become: yes
+  template:
+    src: rhel.repo.j2
+    dest: "/etc/yum.repos.d/{{ item.item.alias }}.repo"
+  register: _override_repos_add_rhel_result
+  with_items: _override_repos_result.results
+  when:
+    - not (item | skipped)
+    - ardana_family == "redhat"
+    - item.item.distro == ardana_distro
+    - item.stat.exists
+  tags:
+    - rhel
+
 - include: _refresh-repos.yml
   when:
     - ((_iso_repos_add_sles_result | changed) or (_iso_repos_add_rhel_result | changed) or
-       (_dir_repos_add_sles_result | changed) or (_dir_repos_add_rhel_result | changed))
+       (_dir_repos_add_sles_result | changed) or (_dir_repos_add_rhel_result | changed) or
+       (_override_repos_add_sles_result | changed) or (_override_repos_add_rhel_result | changed))
